// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cloud_storage.proto

package cloud_storage

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FileType int32

const (
	FileType_Directory FileType = 0
	FileType_File      FileType = 1
)

var FileType_name = map[int32]string{
	0: "Directory",
	1: "File",
}

var FileType_value = map[string]int32{
	"Directory": 0,
	"File":      1,
}

func (x FileType) String() string {
	return proto.EnumName(FileType_name, int32(x))
}

func (FileType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3a81383ce445c343, []int{0}
}

type MinderFile struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Author               string               `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	CreatTime            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=creatTime,proto3" json:"creatTime,omitempty"`
	ModifyTime           *timestamp.Timestamp `protobuf:"bytes,4,opt,name=modifyTime,proto3" json:"modifyTime,omitempty"`
	Data                 string               `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MinderFile) Reset()         { *m = MinderFile{} }
func (m *MinderFile) String() string { return proto.CompactTextString(m) }
func (*MinderFile) ProtoMessage()    {}
func (*MinderFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a81383ce445c343, []int{0}
}

func (m *MinderFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MinderFile.Unmarshal(m, b)
}
func (m *MinderFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MinderFile.Marshal(b, m, deterministic)
}
func (m *MinderFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MinderFile.Merge(m, src)
}
func (m *MinderFile) XXX_Size() int {
	return xxx_messageInfo_MinderFile.Size(m)
}
func (m *MinderFile) XXX_DiscardUnknown() {
	xxx_messageInfo_MinderFile.DiscardUnknown(m)
}

var xxx_messageInfo_MinderFile proto.InternalMessageInfo

func (m *MinderFile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MinderFile) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *MinderFile) GetCreatTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreatTime
	}
	return nil
}

func (m *MinderFile) GetModifyTime() *timestamp.Timestamp {
	if m != nil {
		return m.ModifyTime
	}
	return nil
}

func (m *MinderFile) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type DirReq struct {
	Fullpath             string   `protobuf:"bytes,1,opt,name=fullpath,proto3" json:"fullpath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DirReq) Reset()         { *m = DirReq{} }
func (m *DirReq) String() string { return proto.CompactTextString(m) }
func (*DirReq) ProtoMessage()    {}
func (*DirReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a81383ce445c343, []int{1}
}

func (m *DirReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirReq.Unmarshal(m, b)
}
func (m *DirReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirReq.Marshal(b, m, deterministic)
}
func (m *DirReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirReq.Merge(m, src)
}
func (m *DirReq) XXX_Size() int {
	return xxx_messageInfo_DirReq.Size(m)
}
func (m *DirReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DirReq.DiscardUnknown(m)
}

var xxx_messageInfo_DirReq proto.InternalMessageInfo

func (m *DirReq) GetFullpath() string {
	if m != nil {
		return m.Fullpath
	}
	return ""
}

type FileInfo struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ext                  string               `protobuf:"bytes,2,opt,name=ext,proto3" json:"ext,omitempty"`
	Type                 FileType             `protobuf:"varint,3,opt,name=type,proto3,enum=cloud_storage.FileType" json:"type,omitempty"`
	Hash                 string               `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	Author               string               `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	CreatTime            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=creatTime,proto3" json:"creatTime,omitempty"`
	ModifyTime           *timestamp.Timestamp `protobuf:"bytes,7,opt,name=modifyTime,proto3" json:"modifyTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FileInfo) Reset()         { *m = FileInfo{} }
func (m *FileInfo) String() string { return proto.CompactTextString(m) }
func (*FileInfo) ProtoMessage()    {}
func (*FileInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a81383ce445c343, []int{2}
}

func (m *FileInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileInfo.Unmarshal(m, b)
}
func (m *FileInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileInfo.Marshal(b, m, deterministic)
}
func (m *FileInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileInfo.Merge(m, src)
}
func (m *FileInfo) XXX_Size() int {
	return xxx_messageInfo_FileInfo.Size(m)
}
func (m *FileInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FileInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FileInfo proto.InternalMessageInfo

func (m *FileInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FileInfo) GetExt() string {
	if m != nil {
		return m.Ext
	}
	return ""
}

func (m *FileInfo) GetType() FileType {
	if m != nil {
		return m.Type
	}
	return FileType_Directory
}

func (m *FileInfo) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *FileInfo) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *FileInfo) GetCreatTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreatTime
	}
	return nil
}

func (m *FileInfo) GetModifyTime() *timestamp.Timestamp {
	if m != nil {
		return m.ModifyTime
	}
	return nil
}

func init() {
	proto.RegisterEnum("cloud_storage.FileType", FileType_name, FileType_value)
	proto.RegisterType((*MinderFile)(nil), "cloud_storage.MinderFile")
	proto.RegisterType((*DirReq)(nil), "cloud_storage.DirReq")
	proto.RegisterType((*FileInfo)(nil), "cloud_storage.FileInfo")
}

func init() { proto.RegisterFile("cloud_storage.proto", fileDescriptor_3a81383ce445c343) }

var fileDescriptor_3a81383ce445c343 = []byte{
	// 390 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xdf, 0xab, 0xd3, 0x30,
	0x14, 0xc7, 0x6f, 0x5d, 0x6f, 0x5d, 0xcf, 0xe5, 0x4a, 0xc9, 0x50, 0x6b, 0x5f, 0x1c, 0x9d, 0x0f,
	0xc3, 0x41, 0x06, 0x13, 0x44, 0x7c, 0x9c, 0x43, 0xf0, 0x41, 0x90, 0x6e, 0xef, 0x92, 0xb5, 0xa7,
	0x6d, 0xa0, 0x5d, 0x6a, 0x9a, 0x0e, 0xeb, 0x9f, 0xe7, 0x3f, 0xa6, 0x24, 0xd9, 0xdc, 0x0f, 0x14,
	0xd1, 0xb7, 0x93, 0xe4, 0x7b, 0x7e, 0x7c, 0xbe, 0x39, 0x30, 0x4a, 0x2b, 0xd1, 0x65, 0x9f, 0x5b,
	0x25, 0x24, 0x2b, 0x90, 0x36, 0x52, 0x28, 0x41, 0xee, 0x2f, 0x2e, 0xa3, 0xe7, 0x85, 0x10, 0x45,
	0x85, 0x73, 0xf3, 0xb8, 0xed, 0xf2, 0xb9, 0xe2, 0x35, 0xb6, 0x8a, 0xd5, 0x8d, 0xd5, 0x47, 0x7e,
	0x86, 0xb9, 0x0d, 0xe3, 0xef, 0x0e, 0xc0, 0x47, 0xbe, 0xcb, 0x50, 0xbe, 0xe7, 0x15, 0x12, 0x02,
	0xee, 0x8e, 0xd5, 0x18, 0x3a, 0x63, 0x67, 0xea, 0x27, 0x26, 0x26, 0x4f, 0xc0, 0x63, 0x9d, 0x2a,
	0x85, 0x0c, 0x1f, 0x98, 0xdb, 0xc3, 0x89, 0xbc, 0x01, 0x3f, 0x95, 0xc8, 0xd4, 0x86, 0xd7, 0x18,
	0x0e, 0xc6, 0xce, 0xf4, 0x6e, 0x11, 0x51, 0xdb, 0x9a, 0x1e, 0x5b, 0xd3, 0xcd, 0xb1, 0x75, 0x72,
	0x12, 0x93, 0xb7, 0x00, 0xb5, 0xc8, 0x78, 0xde, 0x9b, 0x54, 0xf7, 0xaf, 0xa9, 0x67, 0x6a, 0x3d,
	0x61, 0xc6, 0x14, 0x0b, 0x6f, 0xed, 0x84, 0x3a, 0x8e, 0x5f, 0x80, 0xb7, 0xe2, 0x32, 0xc1, 0x2f,
	0x24, 0x82, 0x61, 0xde, 0x55, 0x55, 0xc3, 0x54, 0x79, 0x60, 0xf8, 0x75, 0x8e, 0x7f, 0x38, 0x30,
	0xd4, 0x90, 0x1f, 0x76, 0xb9, 0xf8, 0x2d, 0x68, 0x00, 0x03, 0xfc, 0xaa, 0x0e, 0x94, 0x3a, 0x24,
	0x33, 0x70, 0x55, 0xdf, 0x58, 0xba, 0x47, 0x8b, 0xa7, 0xf4, 0xd2, 0x7c, 0x5d, 0x6c, 0xd3, 0x37,
	0x98, 0x18, 0x91, 0x2e, 0x59, 0xb2, 0xb6, 0x34, 0x3c, 0x7e, 0x62, 0xe2, 0x33, 0xef, 0x6e, 0xff,
	0xec, 0x9d, 0xf7, 0xff, 0xde, 0x3d, 0xfc, 0x17, 0xef, 0x5e, 0x4e, 0xac, 0x01, 0x7a, 0x66, 0x72,
	0x0f, 0xfe, 0x8a, 0x4b, 0x4c, 0x95, 0x90, 0x7d, 0x70, 0x43, 0x86, 0xe0, 0xea, 0xa7, 0xc0, 0x59,
	0x7c, 0x83, 0xd1, 0x3b, 0x8d, 0xb9, 0xb6, 0x94, 0x6b, 0x94, 0x7b, 0x9e, 0x22, 0x79, 0x0d, 0xb0,
	0x66, 0x7b, 0xb4, 0xbb, 0x42, 0x9e, 0x5d, 0x59, 0x71, 0x5a, 0xa1, 0xe8, 0x8e, 0xea, 0xed, 0x4a,
	0x9a, 0x34, 0xc1, 0x36, 0xbe, 0x21, 0x33, 0x18, 0xac, 0xb8, 0x24, 0x8f, 0xaf, 0x12, 0xec, 0x7f,
	0x5d, 0x89, 0x97, 0x13, 0x08, 0x52, 0x51, 0xd3, 0x42, 0x22, 0xd2, 0xa2, 0x36, 0x35, 0x97, 0x97,
	0xcb, 0xfd, 0xc9, 0xd9, 0x7a, 0x86, 0xf2, 0xd5, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x64, 0x7d,
	0x68, 0xae, 0x0b, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CloudStorageServiceClient is the client API for CloudStorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CloudStorageServiceClient interface {
	SaveMinder(ctx context.Context, in *MinderFile, opts ...grpc.CallOption) (*RpcRes, error)
	Dir(ctx context.Context, in *DirReq, opts ...grpc.CallOption) (*RpcRes, error)
}

type cloudStorageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCloudStorageServiceClient(cc grpc.ClientConnInterface) CloudStorageServiceClient {
	return &cloudStorageServiceClient{cc}
}

func (c *cloudStorageServiceClient) SaveMinder(ctx context.Context, in *MinderFile, opts ...grpc.CallOption) (*RpcRes, error) {
	out := new(RpcRes)
	err := c.cc.Invoke(ctx, "/cloud_storage.CloudStorageService/SaveMinder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudStorageServiceClient) Dir(ctx context.Context, in *DirReq, opts ...grpc.CallOption) (*RpcRes, error) {
	out := new(RpcRes)
	err := c.cc.Invoke(ctx, "/cloud_storage.CloudStorageService/Dir", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CloudStorageServiceServer is the server API for CloudStorageService service.
type CloudStorageServiceServer interface {
	SaveMinder(context.Context, *MinderFile) (*RpcRes, error)
	Dir(context.Context, *DirReq) (*RpcRes, error)
}

// UnimplementedCloudStorageServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCloudStorageServiceServer struct {
}

func (*UnimplementedCloudStorageServiceServer) SaveMinder(ctx context.Context, req *MinderFile) (*RpcRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveMinder not implemented")
}
func (*UnimplementedCloudStorageServiceServer) Dir(ctx context.Context, req *DirReq) (*RpcRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Dir not implemented")
}

func RegisterCloudStorageServiceServer(s *grpc.Server, srv CloudStorageServiceServer) {
	s.RegisterService(&_CloudStorageService_serviceDesc, srv)
}

func _CloudStorageService_SaveMinder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MinderFile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudStorageServiceServer).SaveMinder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud_storage.CloudStorageService/SaveMinder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudStorageServiceServer).SaveMinder(ctx, req.(*MinderFile))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudStorageService_Dir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DirReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudStorageServiceServer).Dir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud_storage.CloudStorageService/Dir",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudStorageServiceServer).Dir(ctx, req.(*DirReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _CloudStorageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cloud_storage.CloudStorageService",
	HandlerType: (*CloudStorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveMinder",
			Handler:    _CloudStorageService_SaveMinder_Handler,
		},
		{
			MethodName: "Dir",
			Handler:    _CloudStorageService_Dir_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cloud_storage.proto",
}
