// Code generated by protoc-gen-go. DO NOT EDIT.
// source: def.proto

package def

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RpcRes struct {
	R                    uint32   `protobuf:"varint,1,opt,name=r,proto3" json:"r,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcRes) Reset()         { *m = RpcRes{} }
func (m *RpcRes) String() string { return proto.CompactTextString(m) }
func (*RpcRes) ProtoMessage()    {}
func (*RpcRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_76fb0470a3b910d8, []int{0}
}

func (m *RpcRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcRes.Unmarshal(m, b)
}
func (m *RpcRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcRes.Marshal(b, m, deterministic)
}
func (m *RpcRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcRes.Merge(m, src)
}
func (m *RpcRes) XXX_Size() int {
	return xxx_messageInfo_RpcRes.Size(m)
}
func (m *RpcRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcRes.DiscardUnknown(m)
}

var xxx_messageInfo_RpcRes proto.InternalMessageInfo

func (m *RpcRes) GetR() uint32 {
	if m != nil {
		return m.R
	}
	return 0
}

func (m *RpcRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*RpcRes)(nil), "def.RpcRes")
}

func init() { proto.RegisterFile("def.proto", fileDescriptor_76fb0470a3b910d8) }

var fileDescriptor_76fb0470a3b910d8 = []byte{
	// 110 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x49, 0x4d, 0xd3,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x49, 0x4d, 0x53, 0xd2, 0xe0, 0x62, 0x0b, 0x2a,
	0x48, 0x0e, 0x4a, 0x2d, 0x16, 0xe2, 0xe1, 0x62, 0x2c, 0x92, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0d,
	0x62, 0x2c, 0x12, 0x12, 0xe0, 0x62, 0xce, 0x2d, 0x4e, 0x97, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x0c,
	0x02, 0x31, 0x9d, 0x24, 0xb9, 0x04, 0x92, 0xf3, 0x73, 0xf5, 0xd2, 0x8b, 0x52, 0x53, 0xf5, 0xd2,
	0x73, 0x33, 0xf3, 0x52, 0x52, 0x8b, 0x9c, 0x40, 0x46, 0x04, 0x30, 0x26, 0xb1, 0x81, 0x0d, 0x34,
	0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xc9, 0x6a, 0xa6, 0x27, 0x5d, 0x00, 0x00, 0x00,
}
